name: prepare

on:
  schedule:
    # every 19:51 UTC
    - cron: "51 19 * * *"
  workflow_dispatch:

jobs:
  preapre-auto:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout tools
        uses: actions/checkout@v4
        with:
          repository: onlinegears/private-ka-tools
          path: ./private-ka-tools
          ssh-key: ${{ secrets.KEY_FOR_TOOLS }}
      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: private-ka-tools/repo/auto
          push: true
          tags: ghcr.io/${{ github.actor }}/gha-ka-works/auto:latest
