name: works

on:
  schedule:
    # every 21:51 UTC
    - cron: "51 21 * * *"
  workflow_dispatch:

jobs:
  tasks:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout tools
        uses: actions/checkout@v3
        with:
          repository: onlinegears/private-ka-tools
          path: ./private-ka-tools
          ssh-key: ${{ secrets.KEY_FOR_TOOLS }}
      - name: Exec
        run: |
          cd ./private-ka-tools/tools
          ./e run ./ka000 > ../../ka000.log
      - name: Log
        run: |
          d=`date -u "+%Y%m%d%H%M%S"`
          git config user.name "gha"
          git config user.email "action@github.com"
          git checkout -b logs/$d
          git add ka000.log
          git commit -m 'auto commit'
          git push --set-upstream origin logs/$d
